---
abstract: 'Keep script local variables'
author:
  - 'motemen <motemen {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Script-State
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Data::Dumper: 0
  File::Spec: 0
  PadWalker: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/motemen/Script-State.git
version: 0.01
